SELECT SCHEDULE_SEQ.CURRVAL FROM DUAL;

-- totalSchedule
SELECT * FROM SCHEDULE WHERE GID = 1;

-- detailSchedule
SELECT * FROM SCHEDULE WHERE SCD_ID = 11111;

-- 스터디 가입 후 (지나지 않은) 전체 일정 갯수 파악 *달성도 체크용*
SELECT SCD_ID FROM SCHEDULE WHERE GID = 1 AND SCD_END > SYSDATE;

-- 달성
INSERT INTO SCD_ACHIVE VALUES ('11114', 'test1-1', 'N');

-- updateAchive
UPDATE SCD_ACHIVE SET SCD_ACHIVE = 'Y' WHERE SCD_ID = 11114;