SELECT SCHEDULE_SEQ.CURRVAL FROM DUAL;

-- totalSchedule
SELECT * FROM SCHEDULE;
SELECT * FROM SCHEDULE WHERE GID = 1;
SELECT * FROM SCD_ACHIVE;
SELECT MID FROM GSTATUS S WHERE GID = 9;
SELECT SCD_ID FROM SCHEDULE WHERE GID = 14 AND SCD_START >= TO_CHAR(SYSDATE, 'YYYY-MM-DD');
-- detailSchedule
SELECT * FROM SCHEDULE WHERE SCD_ID = 11111;

-- 스터디 가입 후 (지나지 않은) 전체 일정 갯수 파악 *달성도 체크용*
SELECT SCD_ID FROM SCHEDULE WHERE GID = 9 AND SCD_START >= TO_CHAR(SYSDATE, 'YYYY-MM-DD');

-- 달성도 insert 여부 체크
SELECT COUNT(*) FROM SCD_ACHIVE A, SCHEDULE S WHERE A.SCD_ID = S.SCD_ID AND A.SCD_ID = '11164' AND A.MID = 'test3-3' AND S.SCD_START >= TO_CHAR(SYSDATE, 'YYYY-MM-DD');

-- 달성여부 insert
SELECT MID FROM MYGROUP WHERE GID = 1;
SELECT SCD_ID FROM SCHEDULE WHERE GID = 1;
INSERT INTO SCD_ACHIVE VALUES ('11118', 'test1-1', 'N');

SELECT * FROM SCD_ACHIVE;

-- updateAchive
UPDATE SCD_ACHIVE SET SCD_ACHIVE = 'Y' WHERE SCD_ID = 11117 AND MID = 'test1-1';

-- 개인 참여율 확인
SELECT CASE 
    WHEN NVL((SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1), 0) > 0 
    AND NVL((SELECT COUNT(*) FROM SCD_ACHIVE A, SCHEDULE S WHERE A.MID = S.MID AND A.SCD_ID = S.SCD_ID AND SCD_ACHIVE = 'Y' AND S.GID = 1  AND S.MID = 'test1-1'), 0) > 0 
    
    THEN ROUND((SELECT COUNT(*) FROM SCD_ACHIVE A, SCHEDULE S WHERE A.MID = S.MID AND A.SCD_ID = S.SCD_ID AND SCD_ACHIVE = 'Y' AND S.GID = 1 AND S.MID = 'test1-1')
    / (SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1) * 100) ELSE 0 END "rate" FROM DUAL;



SELECT * FROM (SELECT ROWNUM RN, A.*, COALESCE(C.COMMENT_COUNT, 0) AS COMMENT_COUNT
		FROM 
		    (SELECT G.GID, G.GCHARACTER, M.MID, M.MIMAGE, M.MNICKNAME, G.GTITLE, G.GCONTENT, G.GPEOPLE, G.GCURPEOPLE,
		           G.GLANGUAGE1, G.GLANGUAGE2, G.GLANGUAGE3, G.GDEV, G.GDESIGN, G.GPM, G.GRDATE, G.GSDATE, G.GFDATE, G.GHIT, G.GLOC, G.GCOMPLETE 
		    FROM MYGROUP G
		    INNER JOIN MEMBER M ON G.MID = M.MID 
            INNER JOIN GSTATUS S ON S.GID = G.GID 
		    WHERE G.GCOMPLETE = 'N' AND GCHARACTER = 'S'
            AND M.MID = 'test1-1'
            AND S.GSSTATUS = 2 OR S.GSSTATUS = 1
		    ORDER BY G.GID DESC) A
		LEFT JOIN 
		    (SELECT GID, COUNT(*) AS COMMENT_COUNT
		    FROM GCOMMENT
		    GROUP BY GID) C
		ON A.GID = C.GID)
		WHERE RN BETWEEN 1 AND 2;

-- 그룹 평균 참여율 확인
SELECT CASE 
    WHEN NVL((SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1), 0) > 0 
    AND NVL((SELECT COUNT(*) FROM SCD_ACHIVE A, SCHEDULE S WHERE A.MID = S.MID AND A.SCD_ID = S.SCD_ID AND SCD_ACHIVE = 'Y' AND S.GID = 1), 0) > 0 
    
    THEN ROUND((SELECT COUNT(*) FROM SCD_ACHIVE A, SCHEDULE S WHERE A.MID = S.MID AND A.SCD_ID = S.SCD_ID AND SCD_ACHIVE = 'Y' AND S.GID = 1)
    / (SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1) * 100) ELSE 0 END "rate" FROM DUAL;


--SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1 AND SCD_START >= TO_CHAR(SYSDATE, 'YYYY-MM-DD');
--SELECT COUNT(*) FROM SCD_ACHIVE A, SCHEDULE S WHERE A.MID = S.MID AND A.SCD_ID = S.SCD_ID AND SCD_ACHIVE = 'Y' AND S.GID = 1 AND S.SCD_START >= TO_CHAR(SYSDATE, 'YYYY-MM-DD') AND S.MID = 'test1-1';

--SELECT ROUND((CASE WHEN NVL((SELECT COUNT(*) FROM SCD_ACHIVE WHERE SCD_ACHIVE = 'Y' AND MID = 'test1-1'),0) > 0 THEN (SELECT COUNT(*) FROM SCHEDULE WHERE GID = 1) / (SELECT COUNT(*) FROM SCD_ACHIVE WHERE SCD_ACHIVE = 'Y' AND MID = 'test1-1'))*100 ELSE 0 END AS)||'%' "참여율" FROM DUAL;